spring:
  profiles: test

application:
  connectTimeout: 50000
  readTimeout: 50000

---

spring:
  profiles: prod

application:
  connectTimeout: 50000
  readTimeout: 50000

news-service:
  uri: https://newsapi.org/v2/sources
  api-key: e858eefc5ba54ab78ad5cb53e464b6f9
